FROM openjdk:11-jre-slim
WORKDIR usr/src
ADD ./target/SpringAPICloudGateway-0.0.1-SNAPSHOT.jar /usr/src/SpringAPICloudGateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","SpringAPICloudGateway-0.0.1-SNAPSHOT.jar"]