FROM openjdk:11-jre-slim
WORKDIR usr/src
#ENV MONGO_URI=mongodb://localhost:27017/movie_db
ADD ./target/PizzaDetails-0.0.1-SNAPSHOT.jar /usr/src/PizzaDetails-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","PizzaDetails-0.0.1-SNAPSHOT.jar"]
